// GENERATED by scripts/gen-gen3.mjs — do not edit by hand.
//
// Ability descriptions for the 135 Gen 3 species (national dex 252–386, base formes
// only). Sources: @pkmn/dex for battle data, PokéAPI for the growth/catch/EV
// numbers Showdown does not model. Regenerate with:
//     npx vite-node scripts/gen-gen3.mjs

import type { AbilityInfo } from "../abilities";

export const gen3AbilityInfo: Record<string, AbilityInfo> = {
  airLock: { name: "Air Lock", description: "While this Pokemon is active, the effects of weather conditions are disabled." },
  colorChange: { name: "Color Change", description: "This Pokemon's type changes to the type of a move it's hit by, unless it has the type." },
  forecast: { name: "Forecast", description: "Castform's type changes to the current weather condition's type, except Sandstorm." },
  heavyMetal: { name: "Heavy Metal", description: "This Pokemon's weight is doubled." },
  minus: { name: "Minus", description: "If an active ally has this Ability or the Plus Ability, this Pokemon's Sp. Atk is 1.5x." },
  normalize: { name: "Normalize", description: "This Pokemon's moves are changed to be Normal type and have 1.2x power." },
  poisonHeal: { name: "Poison Heal", description: "This Pokemon is healed by 1/8 of its max HP each turn when poisoned; no HP loss." },
  protean: { name: "Protean", description: "This Pokemon's type changes to the type of the move it is using. Once per switch-in." },
  purePower: { name: "Pure Power", description: "This Pokemon's Attack is doubled." },
  roughSkin: { name: "Rough Skin", description: "Pokemon making contact with this Pokemon lose 1/8 of their max HP." },
  simple: { name: "Simple", description: "When one of this Pokemon's stat stages is raised or lowered, the amount is doubled." },
  solidRock: { name: "Solid Rock", description: "This Pokemon receives 3/4 damage from supereffective attacks." },
  stall: { name: "Stall", description: "This Pokemon moves last among Pokemon using the same or greater priority moves." },
  stormDrain: { name: "Storm Drain", description: "This Pokemon draws Water moves to itself to raise Sp. Atk by 1; Water immunity." },
  toxicBoost: { name: "Toxic Boost", description: "While this Pokemon is poisoned, its physical attacks have 1.5x power." },
  truant: { name: "Truant", description: "This Pokemon skips every other turn instead of using a move." },
  whiteSmoke: { name: "White Smoke", description: "Prevents other Pokemon from lowering this Pokemon's stat stages." },
  windRider: { name: "Wind Rider", description: "Attack raised by 1 if hit by a wind move or Tailwind begins. Wind move immunity." },
  wonderGuard: { name: "Wonder Guard", description: "This Pokemon can only be damaged by supereffective moves and indirect damage." },
  wonderSkin: { name: "Wonder Skin", description: "Status moves with accuracy checks are 50% accurate when used on this Pokemon." },
};
