// GENERATED by scripts/pull-fx.mjs — do not edit.
//
// Pokémon Showdown's `BattleEffects`, limited to the sprites we actually
// vendored. See public/fx/PROVENANCE.md for the licence and for what was
// deliberately left out.
//
// ── w/h ARE THE DISPLAY SIZE, NOT THE FILE'S ────────────────────────────
// showEffect scales a sprite by these numbers, and several files on disk are
// a different size on purpose: fireball.png is 32×32 drawn at 64×64 (pixel
// art, doubled), shell.png is 200×183 drawn at 100×91.5 (a 2× asset). Sizing
// from the image's intrinsic dimensions instead would render half of these
// at the wrong scale, so the table is authoritative and the images are told
// what size to be.

export interface FxSprite {
  /** Path under public/. */
  url: string;
  w: number;
  h: number;
}

export const FX_SPRITES: Record<string, FxSprite> = {
  wisp: { url: "/fx/wisp.png", w: 100, h: 100 },
  poisonwisp: { url: "/fx/poisonwisp.png", w: 100, h: 100 },
  waterwisp: { url: "/fx/waterwisp.png", w: 100, h: 100 },
  mudwisp: { url: "/fx/mudwisp.png", w: 100, h: 100 },
  blackwisp: { url: "/fx/blackwisp.png", w: 100, h: 100 },
  fireball: { url: "/fx/fireball.png", w: 64, h: 64 },
  bluefireball: { url: "/fx/bluefireball.png", w: 64, h: 64 },
  rock3: { url: "/fx/rock3.png", w: 66, h: 72 },
  leaf1: { url: "/fx/leaf1.png", w: 32, h: 26 },
  leaf2: { url: "/fx/leaf2.png", w: 40, h: 26 },
  caltrop: { url: "/fx/caltrop.png", w: 80, h: 80 },
  greenmetal1: { url: "/fx/greenmetal1.png", w: 45, h: 45 },
  greenmetal2: { url: "/fx/greenmetal2.png", w: 45, h: 45 },
  poisoncaltrop: { url: "/fx/poisoncaltrop.png", w: 80, h: 80 },
  shadowball: { url: "/fx/shadowball.png", w: 100, h: 100 },
  energyball: { url: "/fx/energyball.png", w: 100, h: 100 },
  electroball: { url: "/fx/electroball.png", w: 100, h: 100 },
  mistball: { url: "/fx/mistball.png", w: 100, h: 100 },
  iceball: { url: "/fx/iceball.png", w: 100, h: 100 },
  flareball: { url: "/fx/flareball.png", w: 100, h: 100 },
  moon: { url: "/fx/moon.png", w: 100, h: 100 },
  pokeball: { url: "/fx/pokeball.png", w: 24, h: 24 },
  fist: { url: "/fx/fist.png", w: 55, h: 49 },
  fist1: { url: "/fx/fist1.png", w: 49, h: 55 },
  foot: { url: "/fx/foot.png", w: 50, h: 75 },
  topbite: { url: "/fx/topbite.png", w: 108, h: 64 },
  bottombite: { url: "/fx/bottombite.png", w: 108, h: 64 },
  web: { url: "/fx/web.png", w: 120, h: 122 },
  leftclaw: { url: "/fx/leftclaw.png", w: 44, h: 60 },
  rightclaw: { url: "/fx/rightclaw.png", w: 44, h: 60 },
  leftslash: { url: "/fx/leftslash.png", w: 57, h: 56 },
  rightslash: { url: "/fx/rightslash.png", w: 57, h: 56 },
  leftchop: { url: "/fx/leftchop.png", w: 100, h: 130 },
  rightchop: { url: "/fx/rightchop.png", w: 100, h: 130 },
  angry: { url: "/fx/angry.png", w: 30, h: 30 },
  heart: { url: "/fx/heart.png", w: 30, h: 30 },
  pointer: { url: "/fx/pointer.png", w: 100, h: 100 },
  sword: { url: "/fx/sword.png", w: 48, h: 100 },
  impact: { url: "/fx/impact.png", w: 127, h: 119 },
  stare: { url: "/fx/stare.png", w: 100, h: 35 },
  shine: { url: "/fx/shine.png", w: 127, h: 119 },
  feather: { url: "/fx/feather.png", w: 100, h: 38 },
  shell: { url: "/fx/shell.png", w: 100, h: 91.5 },
  petal: { url: "/fx/petal.png", w: 60, h: 60 },
  gear: { url: "/fx/gear.png", w: 100, h: 100 },
  rainbow: { url: "/fx/rainbow.png", w: 128, h: 128 },
  hitmark: { url: "/fx/hitmarker.png", w: 100, h: 100 },
};

export type FxSpriteName = keyof typeof FX_SPRITES;
