// Connection graph copied from `game/src/data/regions/kanto/routes.ts`.
// Used by the map editor to draw lines between connected locations so
// admins can see where each route leads. Mirrors the connections field
// on every Route definition — keep in sync when the game's routes
// graph changes (or, eventually, source it from the same backend).

export const DEFAULT_MAP_CONNECTIONS: Record<string, string[]> = {
  indigoPlat:     ["victoryRoad"],
  victoryRoad:    ["route23", "indigoPlat"],
  route23:        ["route22", "victoryRoad"],
  route22:        ["viridianCity", "route23"],
  pewterCity:     ["viridianForest", "route3"],
  viridianForest: ["route2", "pewterCity"],
  route2:         ["viridianCity", "viridianForest", "diglettsCave"],
  viridianCity:   ["route1", "route2", "route22"],
  route1:         ["palletTown", "viridianCity"],
  palletTown:     ["route1", "route21"],
  route21:        ["cinnabarIsland", "palletTown"],
  cinnabarIsland: ["seafoamIslands", "pokemonMansion", "route21"],
  route3:         ["pewterCity", "mtMoon"],
  mtMoon:         ["route3", "route4"],
  route4:         ["mtMoon", "ceruleanCity"],
  ceruleanCity:   ["route4", "route24", "route5", "route9"],
  route9:         ["ceruleanCity", "rockTunnel"],
  rockTunnel:     ["route9", "route10"],
  route24:        ["ceruleanCity", "route25"],
  route25:        ["route24"],
  ceruleanCave:   ["ceruleanCity"],
  route10:        ["rockTunnel", "lavenderTown", "powerPlant"],
  powerPlant:     ["route10"],
  route5:         ["ceruleanCity", "saffronCity"],
  saffronCity:    ["route5", "route6", "route7", "route8"],
  route6:         ["saffronCity", "vermilionCity"],
  vermilionCity:  ["route6", "route11"],
  route7:         ["saffronCity", "celadonCity"],
  celadonCity:    ["route7", "route16"],
  route8:         ["saffronCity", "lavenderTown"],
  lavenderTown:   ["route8", "route10", "pokemonTower", "route12"],
  pokemonTower:   ["lavenderTown"],
  route11:        ["vermilionCity", "diglettsCave", "route12"],
  diglettsCave:   ["route2", "route11"],
  route16:        ["celadonCity", "route17"],
  route17:        ["route16", "route18"],
  route18:        ["route17", "fuchsiaCity"],
  route12:        ["lavenderTown", "route11", "route13"],
  route13:        ["route12", "route14"],
  route14:        ["route13", "route15"],
  route15:        ["route14", "fuchsiaCity"],
  fuchsiaCity:    ["route15", "route18", "safariZone", "route19"],
  safariZone:     ["fuchsiaCity"],
  route19:        ["fuchsiaCity", "route20"],
  route20:        ["route19", "seafoamIslands"],
  seafoamIslands: ["route20", "cinnabarIsland"],
  pokemonMansion: ["cinnabarIsland"],
  raidIsland:     [],
};
