// GENERATED by scripts/gen-hoenn.mjs — do not edit by hand.
//
// Elite Four 106 -> 112, Champion Steven at 115 — the new ceiling.
// Regenerate with:  npx vite-node scripts/gen-hoenn.mjs

import type { GymLeader } from "../../../types";

export const eliteFour: GymLeader[] = [
  {
    id: "sidney",
    name: "Sidney",
    title: "Elite Four",
    locationKey: "everGrandeCity",
    badgeName: "",
    badgeColor: "#4A4A55",
    spriteKey: "sidney-gen3",
    team: [{ speciesKey: "mightyena", level: 106 }, { speciesKey: "shiftry", level: 106 }, { speciesKey: "cacturne", level: 107 }, { speciesKey: "crawdaunt", level: 107 }, { speciesKey: "absol", level: 108 }],
  },
  {
    id: "phoebe",
    name: "Phoebe",
    title: "Elite Four",
    locationKey: "everGrandeCity",
    badgeName: "",
    badgeColor: "#8B6BB1",
    spriteKey: "phoebe-gen3",
    team: [{ speciesKey: "dusclops", level: 107 }, { speciesKey: "banette", level: 108 }, { speciesKey: "sableye", level: 108 }, { speciesKey: "banette", level: 109 }, { speciesKey: "dusclops", level: 109 }],
  },
  {
    id: "glacia",
    name: "Glacia",
    title: "Elite Four",
    locationKey: "everGrandeCity",
    badgeName: "",
    badgeColor: "#7FB8D4",
    spriteKey: "glacia-gen3",
    team: [{ speciesKey: "sealeo", level: 108 }, { speciesKey: "glalie", level: 109 }, { speciesKey: "sealeo", level: 109 }, { speciesKey: "glalie", level: 110 }, { speciesKey: "walrein", level: 111 }],
  },
  {
    id: "drake",
    name: "Drake",
    title: "Elite Four",
    locationKey: "everGrandeCity",
    badgeName: "",
    badgeColor: "#6B4FA8",
    spriteKey: "drake-gen3",
    team: [{ speciesKey: "shelgon", level: 110 }, { speciesKey: "altaria", level: 110 }, { speciesKey: "flygon", level: 111 }, { speciesKey: "flygon", level: 111 }, { speciesKey: "salamence", level: 112 }],
  },
];

export const champion: GymLeader = {
  id: "steven",
  name: "Steven",
  title: "Hoenn Champion",
  locationKey: "everGrandeCity",
  badgeName: "",
  badgeColor: "#8E9BAE",
  spriteKey: "steven-gen3",
  team: [
    { speciesKey: "skarmory", level: 113 },
    { speciesKey: "claydol", level: 113 },
    { speciesKey: "aggron", level: 114 },
    { speciesKey: "cradily", level: 114 },
    { speciesKey: "armaldo", level: 114 },
    { speciesKey: "metagross", level: 115 },
  ],
};
