// GENERATED by scripts/gen-hoenn.mjs — do not edit by hand.
//
// Wild tables. Levels are the FARM band — a first playthrough sees these minus JOURNEY_LEVEL_OFFSET.hoenn (see utils/regionJourney.ts).
// Regenerate with:  npx vite-node scripts/gen-hoenn.mjs

export const encounters: Record<string, { name: string; encounters: { speciesKey: string; weight: number; minLevel: number; maxLevel: number }[] }> = {
  route101: {
    name: "Route 101",
    encounters: [
      { speciesKey: "poochyena", weight: 45, minLevel: 78, maxLevel: 79 },
      { speciesKey: "wurmple", weight: 45, minLevel: 78, maxLevel: 79 },
      { speciesKey: "zigzagoon", weight: 10, minLevel: 78, maxLevel: 79 },
    ],
  },
  route103: {
    name: "Route 103",
    encounters: [
      { speciesKey: "poochyena", weight: 60, minLevel: 78, maxLevel: 79 },
      { speciesKey: "zigzagoon", weight: 20, minLevel: 79, maxLevel: 79 },
      { speciesKey: "wingull", weight: 20, minLevel: 78, maxLevel: 79 },
    ],
  },
  route102: {
    name: "Route 102",
    encounters: [
      { speciesKey: "poochyena", weight: 30, minLevel: 79, maxLevel: 79 },
      { speciesKey: "wurmple", weight: 30, minLevel: 79, maxLevel: 79 },
      { speciesKey: "lotad", weight: 20, minLevel: 79, maxLevel: 79 },
      { speciesKey: "zigzagoon", weight: 15, minLevel: 79, maxLevel: 79 },
      { speciesKey: "ralts", weight: 4, minLevel: 79, maxLevel: 79 },
      { speciesKey: "seedot", weight: 1, minLevel: 79, maxLevel: 79 },
    ],
  },
  petalburgCity: {
    name: "Petalburg City",
    encounters: [
      { speciesKey: "marill", weight: 100, minLevel: 80, maxLevel: 103 },
    ],
  },
  route104: {
    name: "Route 104",
    encounters: [
      { speciesKey: "poochyena", weight: 40, minLevel: 79, maxLevel: 80 },
      { speciesKey: "marill", weight: 20, minLevel: 79, maxLevel: 80 },
      { speciesKey: "wurmple", weight: 20, minLevel: 79, maxLevel: 79 },
      { speciesKey: "taillow", weight: 10, minLevel: 79, maxLevel: 80 },
      { speciesKey: "wingull", weight: 10, minLevel: 79, maxLevel: 80 },
    ],
  },
  petalburgWoods: {
    name: "Petalburg Woods",
    encounters: [
      { speciesKey: "poochyena", weight: 30, minLevel: 80, maxLevel: 81 },
      { speciesKey: "wurmple", weight: 25, minLevel: 80, maxLevel: 81 },
      { speciesKey: "shroomish", weight: 15, minLevel: 80, maxLevel: 81 },
      { speciesKey: "silcoon", weight: 10, minLevel: 80, maxLevel: 80 },
      { speciesKey: "cascoon", weight: 10, minLevel: 80, maxLevel: 80 },
      { speciesKey: "taillow", weight: 5, minLevel: 80, maxLevel: 81 },
      { speciesKey: "slakoth", weight: 5, minLevel: 80, maxLevel: 81 },
    ],
  },
  route116: {
    name: "Route 116",
    encounters: [
      { speciesKey: "poochyena", weight: 28, minLevel: 81, maxLevel: 82 },
      { speciesKey: "taillow", weight: 20, minLevel: 81, maxLevel: 82 },
      { speciesKey: "nincada", weight: 20, minLevel: 81, maxLevel: 82 },
      { speciesKey: "whismur", weight: 20, minLevel: 81, maxLevel: 81 },
      { speciesKey: "abra", weight: 10, minLevel: 82, maxLevel: 82 },
      { speciesKey: "skitty", weight: 2, minLevel: 82, maxLevel: 82 },
    ],
  },
  rusturfTunnel: {
    name: "Rusturf Tunnel",
    encounters: [
      { speciesKey: "whismur", weight: 100, minLevel: 80, maxLevel: 82 },
    ],
  },
  route115: {
    name: "Route 115",
    encounters: [
      { speciesKey: "taillow", weight: 40, minLevel: 94, maxLevel: 95 },
      { speciesKey: "swablu", weight: 30, minLevel: 94, maxLevel: 95 },
      { speciesKey: "jigglypuff", weight: 10, minLevel: 94, maxLevel: 95 },
      { speciesKey: "swellow", weight: 10, minLevel: 95, maxLevel: 95 },
      { speciesKey: "wingull", weight: 10, minLevel: 94, maxLevel: 96 },
    ],
  },
  route105: {
    name: "Route 105",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route106: {
    name: "Route 106",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  dewfordTown: {
    name: "Dewford Town",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  graniteCave: {
    name: "Granite Cave",
    encounters: [
      { speciesKey: "zubat", weight: 120, minLevel: 82, maxLevel: 85 },
      { speciesKey: "makuhita", weight: 110, minLevel: 81, maxLevel: 85 },
      { speciesKey: "aron", weight: 90, minLevel: 82, maxLevel: 85 },
      { speciesKey: "abra", weight: 40, minLevel: 82, maxLevel: 84 },
      { speciesKey: "sableye", weight: 30, minLevel: 83, maxLevel: 85 },
      { speciesKey: "geodude", weight: 10, minLevel: 81, maxLevel: 83 },
    ],
  },
  route107: {
    name: "Route 107",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route108: {
    name: "Route 108",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route109: {
    name: "Route 109",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  slateportCity: {
    name: "Slateport City",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route110: {
    name: "Route 110",
    encounters: [
      { speciesKey: "electrike", weight: 30, minLevel: 85, maxLevel: 86 },
      { speciesKey: "poochyena", weight: 20, minLevel: 85, maxLevel: 85 },
      { speciesKey: "minun", weight: 15, minLevel: 86, maxLevel: 86 },
      { speciesKey: "gulpin", weight: 15, minLevel: 85, maxLevel: 86 },
      { speciesKey: "oddish", weight: 10, minLevel: 86, maxLevel: 86 },
      { speciesKey: "wingull", weight: 8, minLevel: 85, maxLevel: 85 },
      { speciesKey: "plusle", weight: 2, minLevel: 85, maxLevel: 86 },
    ],
  },
  route117: {
    name: "Route 117",
    encounters: [
      { speciesKey: "oddish", weight: 40, minLevel: 86, maxLevel: 87 },
      { speciesKey: "poochyena", weight: 30, minLevel: 86, maxLevel: 87 },
      { speciesKey: "illumise", weight: 18, minLevel: 86, maxLevel: 87 },
      { speciesKey: "marill", weight: 10, minLevel: 86, maxLevel: 86 },
      { speciesKey: "seedot", weight: 1, minLevel: 86, maxLevel: 86 },
      { speciesKey: "volbeat", weight: 1, minLevel: 86, maxLevel: 86 },
    ],
  },
  route111: {
    name: "Route 111",
    encounters: [
      { speciesKey: "sandshrew", weight: 35, minLevel: 91, maxLevel: 92 },
      { speciesKey: "trapinch", weight: 35, minLevel: 91, maxLevel: 92 },
      { speciesKey: "baltoy", weight: 24, minLevel: 91, maxLevel: 92 },
      { speciesKey: "cacnea", weight: 6, minLevel: 91, maxLevel: 93 },
    ],
  },
  route112: {
    name: "Route 112",
    encounters: [
      { speciesKey: "numel", weight: 75, minLevel: 87, maxLevel: 88 },
      { speciesKey: "marill", weight: 25, minLevel: 87, maxLevel: 88 },
    ],
  },
  fieryPath: {
    name: "Fiery Path",
    encounters: [
      { speciesKey: "numel", weight: 30, minLevel: 88, maxLevel: 88 },
      { speciesKey: "koffing", weight: 25, minLevel: 88, maxLevel: 88 },
      { speciesKey: "torkoal", weight: 18, minLevel: 87, maxLevel: 88 },
      { speciesKey: "machop", weight: 15, minLevel: 88, maxLevel: 88 },
      { speciesKey: "slugma", weight: 10, minLevel: 88, maxLevel: 88 },
      { speciesKey: "grimer", weight: 2, minLevel: 87, maxLevel: 87 },
    ],
  },
  route113: {
    name: "Route 113",
    encounters: [
      { speciesKey: "spinda", weight: 70, minLevel: 87, maxLevel: 88 },
      { speciesKey: "slugma", weight: 25, minLevel: 87, maxLevel: 88 },
      { speciesKey: "skarmory", weight: 5, minLevel: 88, maxLevel: 88 },
    ],
  },
  route114: {
    name: "Route 114",
    encounters: [
      { speciesKey: "swablu", weight: 40, minLevel: 88, maxLevel: 89 },
      { speciesKey: "lotad", weight: 30, minLevel: 88, maxLevel: 88 },
      { speciesKey: "lombre", weight: 20, minLevel: 88, maxLevel: 90 },
      { speciesKey: "seviper", weight: 9, minLevel: 88, maxLevel: 89 },
      { speciesKey: "nuzleaf", weight: 1, minLevel: 88, maxLevel: 88 },
    ],
  },
  meteorFalls: {
    name: "Meteor Falls",
    encounters: [
      { speciesKey: "golbat", weight: 180, minLevel: 101, maxLevel: 106 },
      { speciesKey: "solrock", weight: 115, minLevel: 87, maxLevel: 106 },
      { speciesKey: "zubat", weight: 80, minLevel: 87, maxLevel: 91 },
      { speciesKey: "bagon", weight: 25, minLevel: 95, maxLevel: 103 },
    ],
  },
  jaggedPass: {
    name: "Jagged Pass",
    encounters: [
      { speciesKey: "numel", weight: 55, minLevel: 91, maxLevel: 93 },
      { speciesKey: "machop", weight: 25, minLevel: 91, maxLevel: 93 },
      { speciesKey: "spoink", weight: 20, minLevel: 91, maxLevel: 93 },
    ],
  },
  route118: {
    name: "Route 118",
    encounters: [
      { speciesKey: "zigzagoon", weight: 30, minLevel: 94, maxLevel: 96 },
      { speciesKey: "electrike", weight: 30, minLevel: 94, maxLevel: 96 },
      { speciesKey: "wingull", weight: 19, minLevel: 95, maxLevel: 97 },
      { speciesKey: "linoone", weight: 10, minLevel: 96, maxLevel: 96 },
      { speciesKey: "manectric", weight: 10, minLevel: 96, maxLevel: 96 },
      { speciesKey: "kecleon", weight: 1, minLevel: 95, maxLevel: 95 },
    ],
  },
  route119: {
    name: "Route 119",
    encounters: [
      { speciesKey: "oddish", weight: 30, minLevel: 94, maxLevel: 97 },
      { speciesKey: "zigzagoon", weight: 30, minLevel: 95, maxLevel: 97 },
      { speciesKey: "linoone", weight: 30, minLevel: 95, maxLevel: 97 },
      { speciesKey: "tropius", weight: 9, minLevel: 95, maxLevel: 97 },
      { speciesKey: "kecleon", weight: 1, minLevel: 95, maxLevel: 95 },
    ],
  },
  route120: {
    name: "Route 120",
    encounters: [
      { speciesKey: "mightyena", weight: 30, minLevel: 95, maxLevel: 97 },
      { speciesKey: "oddish", weight: 25, minLevel: 95, maxLevel: 97 },
      { speciesKey: "poochyena", weight: 20, minLevel: 95, maxLevel: 95 },
      { speciesKey: "marill", weight: 15, minLevel: 95, maxLevel: 97 },
      { speciesKey: "absol", weight: 8, minLevel: 95, maxLevel: 97 },
      { speciesKey: "seedot", weight: 1, minLevel: 95, maxLevel: 95 },
      { speciesKey: "kecleon", weight: 1, minLevel: 95, maxLevel: 95 },
    ],
  },
  route121: {
    name: "Route 121",
    encounters: [
      { speciesKey: "shuppet", weight: 30, minLevel: 96, maxLevel: 97 },
      { speciesKey: "poochyena", weight: 20, minLevel: 96, maxLevel: 96 },
      { speciesKey: "mightyena", weight: 20, minLevel: 96, maxLevel: 97 },
      { speciesKey: "oddish", weight: 15, minLevel: 96, maxLevel: 97 },
      { speciesKey: "wingull", weight: 9, minLevel: 96, maxLevel: 97 },
      { speciesKey: "gloom", weight: 5, minLevel: 97, maxLevel: 97 },
      { speciesKey: "kecleon", weight: 1, minLevel: 95, maxLevel: 95 },
    ],
  },
  lilycoveCity: {
    name: "Lilycove City",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route122: {
    name: "Route 122",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  mtPyre: {
    name: "Mt. Pyre",
    encounters: [
      { speciesKey: "shuppet", weight: 715, minLevel: 93, maxLevel: 99 },
      { speciesKey: "duskull", weight: 43, minLevel: 95, maxLevel: 99 },
      { speciesKey: "vulpix", weight: 30, minLevel: 95, maxLevel: 98 },
      { speciesKey: "wingull", weight: 10, minLevel: 96, maxLevel: 97 },
      { speciesKey: "chimecho", weight: 2, minLevel: 97, maxLevel: 97 },
    ],
  },
  route123: {
    name: "Route 123",
    encounters: [
      { speciesKey: "shuppet", weight: 30, minLevel: 96, maxLevel: 97 },
      { speciesKey: "poochyena", weight: 20, minLevel: 96, maxLevel: 96 },
      { speciesKey: "mightyena", weight: 20, minLevel: 96, maxLevel: 97 },
      { speciesKey: "oddish", weight: 15, minLevel: 96, maxLevel: 97 },
      { speciesKey: "wingull", weight: 9, minLevel: 96, maxLevel: 97 },
      { speciesKey: "gloom", weight: 5, minLevel: 97, maxLevel: 97 },
      { speciesKey: "kecleon", weight: 1, minLevel: 95, maxLevel: 95 },
    ],
  },
  route124: {
    name: "Route 124",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  mossdeepCity: {
    name: "Mossdeep City",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route125: {
    name: "Route 125",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  shoalCave: {
    name: "Shoal Cave",
    encounters: [
      { speciesKey: "spheal", weight: 245, minLevel: 96, maxLevel: 100 },
      { speciesKey: "zubat", weight: 220, minLevel: 96, maxLevel: 100 },
      { speciesKey: "golbat", weight: 25, minLevel: 99, maxLevel: 100 },
      { speciesKey: "snorunt", weight: 10, minLevel: 96, maxLevel: 99 },
    ],
  },
  route126: {
    name: "Route 126",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  sootopolisCity: {
    name: "Sootopolis City",
    encounters: [
      { speciesKey: "magikarp", weight: 100, minLevel: 80, maxLevel: 103 },
    ],
  },
  caveOfOrigin: {
    name: "Cave of Origin",
    encounters: [
      { speciesKey: "zubat", weight: 330, minLevel: 97, maxLevel: 103 },
      { speciesKey: "sableye", weight: 120, minLevel: 99, maxLevel: 102 },
      { speciesKey: "golbat", weight: 50, minLevel: 101, maxLevel: 103 },
    ],
  },
  route127: {
    name: "Route 127",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route128: {
    name: "Route 128",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  seafloorCavern: {
    name: "Seafloor Cavern",
    encounters: [
      { speciesKey: "zubat", weight: 90, minLevel: 97, maxLevel: 103 },
      { speciesKey: "golbat", weight: 10, minLevel: 101, maxLevel: 103 },
    ],
  },
  route129: {
    name: "Route 129",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 4, minLevel: 95, maxLevel: 99 },
      { speciesKey: "wailord", weight: 1, minLevel: 95, maxLevel: 99 },
    ],
  },
  route130: {
    name: "Route 130",
    encounters: [
      { speciesKey: "wynaut", weight: 100, minLevel: 80, maxLevel: 110 },
    ],
  },
  route131: {
    name: "Route 131",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  pacifidlogTown: {
    name: "Pacifidlog Town",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  skyPillar: {
    name: "Sky Pillar",
    encounters: [
      { speciesKey: "golbat", weight: 90, minLevel: 102, maxLevel: 103 },
      { speciesKey: "sableye", weight: 90, minLevel: 101, maxLevel: 102 },
      { speciesKey: "claydol", weight: 69, minLevel: 103, maxLevel: 105 },
      { speciesKey: "banette", weight: 45, minLevel: 104, maxLevel: 105 },
      { speciesKey: "altaria", weight: 6, minLevel: 105, maxLevel: 106 },
    ],
  },
  route132: {
    name: "Route 132",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route133: {
    name: "Route 133",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  route134: {
    name: "Route 134",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  everGrandeCity: {
    name: "Ever Grande City",
    encounters: [
      { speciesKey: "tentacool", weight: 60, minLevel: 80, maxLevel: 103 },
      { speciesKey: "wingull", weight: 35, minLevel: 84, maxLevel: 99 },
      { speciesKey: "pelipper", weight: 5, minLevel: 95, maxLevel: 99 },
    ],
  },
  victoryRoadHoenn: {
    name: "Victory Road",
    encounters: [
      { speciesKey: "golbat", weight: 95, minLevel: 105, maxLevel: 109 },
      { speciesKey: "hariyama", weight: 60, minLevel: 105, maxLevel: 108 },
      { speciesKey: "lairon", weight: 60, minLevel: 106, maxLevel: 109 },
      { speciesKey: "sableye", weight: 35, minLevel: 106, maxLevel: 109 },
      { speciesKey: "zubat", weight: 10, minLevel: 103, maxLevel: 103 },
      { speciesKey: "loudred", weight: 10, minLevel: 106, maxLevel: 106 },
      { speciesKey: "makuhita", weight: 10, minLevel: 103, maxLevel: 103 },
      { speciesKey: "mawile", weight: 10, minLevel: 105, maxLevel: 109 },
    ],
  },
};
