// GENERATED by scripts/gen-hoenn.mjs — do not edit by hand.
//
// Eight gyms, 78 -> 104. Sits directly above Johto's 48 -> 75 band.
// Regenerate with:  npx vite-node scripts/gen-hoenn.mjs

import type { GymLeader } from "../../../types";

export const gymLeaders: GymLeader[] = [
  {
    id: "roxanne",
    name: "Roxanne",
    title: "Rustboro City Gym Leader",
    locationKey: "rustboroCity",
    badgeName: "Stone Badge",
    badgeColor: "#B0A18C",
    spriteKey: "roxanne-gen3",
    team: [{ speciesKey: "geodude", level: 78 }, { speciesKey: "geodude", level: 78 }, { speciesKey: "nosepass", level: 80 }],
  },
  {
    id: "brawly",
    name: "Brawly",
    title: "Dewford Town Gym Leader",
    locationKey: "dewfordTown",
    badgeName: "Knuckle Badge",
    badgeColor: "#C96A3A",
    spriteKey: "brawly-gen3",
    team: [{ speciesKey: "machop", level: 82 }, { speciesKey: "makuhita", level: 84 }],
  },
  {
    id: "wattson",
    name: "Wattson",
    title: "Mauville City Gym Leader",
    locationKey: "mauvilleCity",
    badgeName: "Dynamo Badge",
    badgeColor: "#E8C63A",
    spriteKey: "wattson-gen3",
    team: [{ speciesKey: "magnemite", level: 86 }, { speciesKey: "voltorb", level: 86 }, { speciesKey: "magneton", level: 88 }],
  },
  {
    id: "flannery",
    name: "Flannery",
    title: "Lavaridge Town Gym Leader",
    locationKey: "lavaridgeTown",
    badgeName: "Heat Badge",
    badgeColor: "#D2452F",
    spriteKey: "flannery-gen3",
    team: [{ speciesKey: "slugma", level: 89 }, { speciesKey: "slugma", level: 89 }, { speciesKey: "camerupt", level: 90 }, { speciesKey: "torkoal", level: 92 }],
  },
  {
    id: "norman",
    name: "Norman",
    title: "Petalburg City Gym Leader",
    locationKey: "petalburgCity",
    badgeName: "Balance Badge",
    badgeColor: "#9AA0A6",
    spriteKey: "norman-gen3",
    team: [{ speciesKey: "slaking", level: 93 }, { speciesKey: "vigoroth", level: 94 }, { speciesKey: "slaking", level: 96 }],
  },
  {
    id: "winona",
    name: "Winona",
    title: "Fortree City Gym Leader",
    locationKey: "fortreeCity",
    badgeName: "Feather Badge",
    badgeColor: "#8FB8E8",
    spriteKey: "winona-gen3",
    team: [{ speciesKey: "swablu", level: 96 }, { speciesKey: "tropius", level: 96 }, { speciesKey: "pelipper", level: 97 }, { speciesKey: "skarmory", level: 98 }, { speciesKey: "altaria", level: 99 }],
  },
  {
    id: "tateAndLiza",
    name: "Tate & Liza",
    title: "Mossdeep City Gym Leader",
    locationKey: "mossdeepCity",
    badgeName: "Mind Badge",
    badgeColor: "#C48BD9",
    spriteKey: "tateandliza-gen3",
    team: [{ speciesKey: "lunatone", level: 100 }, { speciesKey: "solrock", level: 101 }],
  },
  {
    id: "wallace",
    name: "Wallace",
    title: "Sootopolis City Gym Leader",
    locationKey: "sootopolisCity",
    badgeName: "Rain Badge",
    badgeColor: "#4FA8C7",
    spriteKey: "wallace-gen3",
    team: [{ speciesKey: "luvdisc", level: 101 }, { speciesKey: "whiscash", level: 102 }, { speciesKey: "sealeo", level: 102 }, { speciesKey: "seaking", level: 103 }, { speciesKey: "milotic", level: 104 }],
  },
];
