// GENERATED by scripts/gen-hoenn.mjs — do not edit by hand.
//
// The region object.
// Regenerate with:  npx vite-node scripts/gen-hoenn.mjs

import type { Region } from "../types";
import { routes } from "./routes";
import { encounters } from "./encounters";
import { gymLeaders } from "./gymLeaders";
import { eliteFour, champion } from "./eliteFour";
import { trainerEncounters } from "./trainerEncounters";
import { shops } from "./shops";

// Hoenn — unlocked after beating Johto's Champion. Littleroot Town carries the
// actual gate (`unlock: { championDefeated: true }` in routes.ts); the
// `unlockCondition` below states the same relationship on the Region object,
// per the checklist in regions/types.ts.
//
// NOT added to LEGACY_REGIONS in utils/regionJourney.ts, and that is the whole
// point of the journey system: a Pokemon with no recorded origin counts as
// native to Kanto and Johto only, so an established box cannot walk into Hoenn
// and flatten it. That list is frozen.
export const hoenn: Region = {
  id: "hoenn",
  name: "Hoenn",
  starters: ["treecko", "torchic", "mudkip"],
  startingLocation: "littlerootTown",
  unlockCondition: { championDefeatedIn: "johto" },
  routes,
  encounters,
  gymLeaders,
  eliteFour,
  champion,
  trainerEncounters,
  shops,
};
