// GENERATED by scripts/gen-hoenn.mjs — do not edit by hand.
//
// Marts. No TMs — machines are sold only at the TM Mart, on a daily rotation.
// Regenerate with:  npx vite-node scripts/gen-hoenn.mjs

import type { ShopDef } from "../../../types";

export const shops: Record<string, ShopDef> = {
  oldaleTown: {
    name: "Oldale Mart",
    items: [
      { itemId: "pokeball" },
    ],
  },
  petalburgCity: {
    name: "Petalburg Mart",
    items: [
      { itemId: "pokeball" },
      { itemId: "greatball", unlockWildBattlesWon: 50 },
    ],
  },
  rustboroCity: {
    name: "Rustboro Mart",
    items: [
      { itemId: "pokeball" },
      { itemId: "greatball", unlockWildBattlesWon: 40 },
    ],
  },
  slateportCity: {
    name: "Slateport Market",
    items: [
      { itemId: "pokeball" },
      { itemId: "greatball" },
      { itemId: "ultraball", unlockWildBattlesWon: 220 },
    ],
  },
  mauvilleCity: {
    name: "Mauville Mart",
    items: [
      { itemId: "pokeball" },
      { itemId: "greatball" },
      { itemId: "ultraball", unlockWildBattlesWon: 180 },
    ],
  },
  lavaridgeTown: {
    name: "Lavaridge Mart",
    items: [
      { itemId: "greatball" },
      { itemId: "ultraball", unlockWildBattlesWon: 150 },
    ],
  },
  fortreeCity: {
    name: "Fortree Mart",
    items: [
      { itemId: "greatball" },
      { itemId: "ultraball", unlockWildBattlesWon: 120 },
    ],
  },
  lilycoveCity: {
    name: "Lilycove Department Store",
    items: [
      { itemId: "pokeball" },
      { itemId: "greatball" },
      { itemId: "ultraball" },
    ],
  },
  mossdeepCity: {
    name: "Mossdeep Mart",
    items: [
      { itemId: "greatball" },
      { itemId: "ultraball" },
    ],
  },
  sootopolisCity: {
    name: "Sootopolis Mart",
    items: [
      { itemId: "ultraball" },
    ],
  },
  everGrandeCity: {
    name: "Ever Grande Mart",
    items: [
      { itemId: "ultraball" },
    ],
  },
};
