// GENERATED by scripts/gen-hoenn.mjs — do not edit by hand.
//
// Town rosters. Towns have no wild encounters, so these are the ONLY source of battles-won at a town — and the unlock chain runs on exactly that. Without them the region dead-ends at Littleroot.
// Regenerate with:  npx vite-node scripts/gen-hoenn.mjs

import type { TrainerEncounter } from "../../../types";

export const trainerEncounters: Record<string, TrainerEncounter[]> = {
  littlerootTown: [
    { id: "littlerootTown_1", name: "May", trainerClass: "youngster", team: [{ speciesKey: "torchic", level: 78 }] },
    { id: "littlerootTown_2", name: "Rival Brendan", trainerClass: "youngster", team: [{ speciesKey: "mudkip", level: 79 }, { speciesKey: "zigzagoon", level: 78 }] },
    { id: "littlerootTown_3", name: "Prof. Aide", trainerClass: "youngster", team: [{ speciesKey: "poochyena", level: 78 }] },
  ],
  oldaleTown: [
    { id: "oldaleTown_1", name: "Youngster Calvin", trainerClass: "youngster", team: [{ speciesKey: "poochyena", level: 80 }, { speciesKey: "zigzagoon", level: 80 }] },
    { id: "oldaleTown_2", name: "Lass Tiana", trainerClass: "lass", team: [{ speciesKey: "wurmple", level: 80 }] },
    { id: "oldaleTown_3", name: "Bug Catcher Rick", trainerClass: "bugcatcher", team: [{ speciesKey: "wurmple", level: 81 }] },
  ],
  petalburgCity: [
    { id: "petalburgCity_1", name: "Rich Boy Winston", trainerClass: "gentleman", team: [{ speciesKey: "zigzagoon", level: 82 }] },
    { id: "petalburgCity_2", name: "Lady Cindy", trainerClass: "lass", team: [{ speciesKey: "zigzagoon", level: 82 }] },
    { id: "petalburgCity_3", name: "Scientist Ivan", trainerClass: "scientist", team: [{ speciesKey: "magnemite", level: 83 }] },
  ],
  rustboroCity: [
    { id: "rustboroCity_1", name: "School Kid Georgia", trainerClass: "youngster", team: [{ speciesKey: "shroomish", level: 84 }] },
    { id: "rustboroCity_2", name: "Hiker Marc", trainerClass: "hiker", team: [{ speciesKey: "geodude", level: 85 }, { speciesKey: "aron", level: 85 }] },
    { id: "rustboroCity_3", name: "Youngster Josh", trainerClass: "youngster", team: [{ speciesKey: "nincada", level: 84 }] },
  ],
  verdanturfTown: [
    { id: "verdanturfTown_1", name: "Battle Girl Vivian", trainerClass: "blackbelt", team: [{ speciesKey: "meditite", level: 88 }] },
    { id: "verdanturfTown_2", name: "Youngster Haley", trainerClass: "youngster", team: [{ speciesKey: "skitty", level: 88 }] },
    { id: "verdanturfTown_3", name: "Bug Maniac Brandon", trainerClass: "bugcatcher", team: [{ speciesKey: "nincada", level: 89 }] },
  ],
  dewfordTown: [
    { id: "dewfordTown_1", name: "Black Belt Takao", trainerClass: "blackbelt", team: [{ speciesKey: "makuhita", level: 87 }] },
    { id: "dewfordTown_2", name: "Fisherman Elliot", trainerClass: "fisherman", team: [{ speciesKey: "magikarp", level: 86 }, { speciesKey: "tentacool", level: 87 }] },
    { id: "dewfordTown_3", name: "Sailor Huey", trainerClass: "sailor", team: [{ speciesKey: "machop", level: 87 }] },
  ],
  slateportCity: [
    { id: "slateportCity_1", name: "Sailor Dwayne", trainerClass: "sailor", team: [{ speciesKey: "wingull", level: 89 }] },
    { id: "slateportCity_2", name: "Tuber Ricky", trainerClass: "youngster", team: [{ speciesKey: "azurill", level: 88 }] },
    { id: "slateportCity_3", name: "Collector Edwin", trainerClass: "gentleman", team: [{ speciesKey: "gulpin", level: 89 }] },
  ],
  mauvilleCity: [
    { id: "mauvilleCity_1", name: "Guitarist Kirk", trainerClass: "youngster", team: [{ speciesKey: "electrike", level: 91 }] },
    { id: "mauvilleCity_2", name: "Bug Maniac Angelo", trainerClass: "bugcatcher", team: [{ speciesKey: "nincada", level: 90 }] },
    { id: "mauvilleCity_3", name: "Youngster Wattson Fan", trainerClass: "youngster", team: [{ speciesKey: "voltorb", level: 91 }] },
  ],
  fallarborTown: [
    { id: "fallarborTown_1", name: "Hiker Trent", trainerClass: "hiker", team: [{ speciesKey: "geodude", level: 92 }, { speciesKey: "numel", level: 92 }] },
    { id: "fallarborTown_2", name: "Beauty Sheila", trainerClass: "beauty", team: [{ speciesKey: "spinda", level: 92 }] },
    { id: "fallarborTown_3", name: "Ruin Maniac Andres", trainerClass: "hiker", team: [{ speciesKey: "baltoy", level: 93 }] },
  ],
  lavaridgeTown: [
    { id: "lavaridgeTown_1", name: "Hiker Lenny", trainerClass: "hiker", team: [{ speciesKey: "numel", level: 94 }] },
    { id: "lavaridgeTown_2", name: "Kindler Cole", trainerClass: "firebreather", team: [{ speciesKey: "slugma", level: 94 }] },
    { id: "lavaridgeTown_3", name: "Battle Girl Danielle", trainerClass: "blackbelt", team: [{ speciesKey: "machoke", level: 95 }] },
  ],
  fortreeCity: [
    { id: "fortreeCity_1", name: "Bird Keeper Coby", trainerClass: "birdkeeper", team: [{ speciesKey: "swellow", level: 97 }] },
    { id: "fortreeCity_2", name: "Ninja Boy Lung", trainerClass: "ninja", team: [{ speciesKey: "nincada", level: 96 }] },
    { id: "fortreeCity_3", name: "Camper Branden", trainerClass: "camper", team: [{ speciesKey: "linoone", level: 96 }] },
  ],
  lilycoveCity: [
    { id: "lilycoveCity_1", name: "Beauty Bridget", trainerClass: "beauty", team: [{ speciesKey: "gloom", level: 98 }] },
    { id: "lilycoveCity_2", name: "Pokéfan Vanessa", trainerClass: "gentleman", team: [{ speciesKey: "skitty", level: 98 }] },
    { id: "lilycoveCity_3", name: "Sailor Edmond", trainerClass: "sailor", team: [{ speciesKey: "wingull", level: 99 }] },
  ],
  mossdeepCity: [
    { id: "mossdeepCity_1", name: "Psychic Cameron", trainerClass: "psychic", team: [{ speciesKey: "kadabra", level: 101 }] },
    { id: "mossdeepCity_2", name: "Gentleman Everett", trainerClass: "gentleman", team: [{ speciesKey: "xatu", level: 101 }] },
    { id: "mossdeepCity_3", name: "Ninja Boy Yasu", trainerClass: "ninja", team: [{ speciesKey: "ninjask", level: 100 }] },
  ],
  sootopolisCity: [
    { id: "sootopolisCity_1", name: "Swimmer Beverly", trainerClass: "swimmer", team: [{ speciesKey: "luvdisc", level: 103 }] },
    { id: "sootopolisCity_2", name: "Beauty Callie", trainerClass: "beauty", team: [{ speciesKey: "milotic", level: 104 }] },
    { id: "sootopolisCity_3", name: "Fisherman Nolan", trainerClass: "fisherman", team: [{ speciesKey: "whiscash", level: 103 }] },
  ],
  pacifidlogTown: [
    { id: "pacifidlogTown_1", name: "Swimmer Tony", trainerClass: "swimmer", team: [{ speciesKey: "wailmer", level: 106 }] },
    { id: "pacifidlogTown_2", name: "Fisherman Barny", trainerClass: "fisherman", team: [{ speciesKey: "luvdisc", level: 105 }] },
    { id: "pacifidlogTown_3", name: "Sailor Duncan", trainerClass: "sailor", team: [{ speciesKey: "tentacruel", level: 106 }] },
  ],
  everGrandeCity: [
    { id: "everGrandeCity_1", name: "Cooltrainer Vito", trainerClass: "cooltrainer", team: [{ speciesKey: "swellow", level: 109 }, { speciesKey: "kadabra", level: 109 }] },
    { id: "everGrandeCity_2", name: "Cooltrainer Michelle", trainerClass: "cooltrainer", team: [{ speciesKey: "hariyama", level: 110 }] },
    { id: "everGrandeCity_3", name: "Cooltrainer Owen", trainerClass: "cooltrainer", team: [{ speciesKey: "lairon", level: 110 }] },
  ],
};
